services:
  - type: web
    name: ocupasaludlab-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn ocupasaludlab.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ocupasaludlab-db
          property: connectionString
databases:
  - name: ocupasaludlab-db
    databaseName: ocupasaludlab
    user: postgres
    